title: V.A.P.E.R. Docs
description: Documentation for the VAPER pipeline
theme: just-the-docs

url: https://github.com/DOH-JDJ0303/vaper-docs

baseurl: "/vaper-docs"

favicon_ico: "/assets/images/vaper-logo.ico"

aux_links:
  VAPER GitHub: https://github.com/DOH-JDJ0303/vaper

callouts:
  note:
    title: Note
    color: blue
  tip:
    title: Tip
    color: green
  important:
    title: Important
    color: purple
  warning:
    title: Warning
    color: red
  example:
    title: Example
    color: yellow